import { forwardRef, type ComponentProps } from 'react';
import { HugeiconsIcon } from '@hugeicons/react';
import Add01Icon from '@hugeicons/core-free-icons/Add01Icon';
import Alert02Icon from '@hugeicons/core-free-icons/Alert02Icon';
import ArrowDown01Icon from '@hugeicons/core-free-icons/ArrowDown01Icon';
import ArrowRight02Icon from '@hugeicons/core-free-icons/ArrowRight02Icon';
import ArrowUp01Icon from '@hugeicons/core-free-icons/ArrowUp01Icon';
import BellIcon from '@hugeicons/core-free-icons/BellIcon';
import Calendar01Icon from '@hugeicons/core-free-icons/Calendar01Icon';
import Calendar03Icon from '@hugeicons/core-free-icons/Calendar03Icon';
import Cancel01Icon from '@hugeicons/core-free-icons/Cancel01Icon';
import CheckmarkSquare02Icon from '@hugeicons/core-free-icons/CheckmarkSquare02Icon';
import ChevronDownIcon from '@hugeicons/core-free-icons/ChevronDownIcon';
import ChevronLeftIcon from '@hugeicons/core-free-icons/ChevronLeftIcon';
import ChevronRightIcon from '@hugeicons/core-free-icons/ChevronRightIcon';
import Clock01Icon from '@hugeicons/core-free-icons/Clock01Icon';
import Delete02Icon from '@hugeicons/core-free-icons/Delete02Icon';
import EraserIcon from '@hugeicons/core-free-icons/EraserIcon';
import FireIcon from '@hugeicons/core-free-icons/FireIcon';
import Folder01Icon from '@hugeicons/core-free-icons/Folder01Icon';
import FrownIcon from '@hugeicons/core-free-icons/FrownIcon';
import GripVerticalIcon from '@hugeicons/core-free-icons/GripVerticalIcon';
import HeartIcon from '@hugeicons/core-free-icons/HeartIcon';
import HelpCircleIcon from '@hugeicons/core-free-icons/HelpCircleIcon';
import Layers01Icon from '@hugeicons/core-free-icons/Layers01Icon';
import MehIcon from '@hugeicons/core-free-icons/MehIcon';
import MoveRightIcon from '@hugeicons/core-free-icons/MoveRightIcon';
import PencilEdit02Icon from '@hugeicons/core-free-icons/PencilEdit02Icon';
import RefreshIcon from '@hugeicons/core-free-icons/RefreshIcon';
import RepeatIcon from '@hugeicons/core-free-icons/RepeatIcon';
import Settings01Icon from '@hugeicons/core-free-icons/Settings01Icon';
import Shield02Icon from '@hugeicons/core-free-icons/Shield02Icon';
import SmileIcon from '@hugeicons/core-free-icons/SmileIcon';
import Sorting01Icon from '@hugeicons/core-free-icons/Sorting01Icon';
import StopIcon from '@hugeicons/core-free-icons/StopIcon';
import Task01Icon from '@hugeicons/core-free-icons/Task01Icon';
import Tick02Icon from '@hugeicons/core-free-icons/Tick02Icon';
import ViewIcon from '@hugeicons/core-free-icons/ViewIcon';
import ViewOffSlashIcon from '@hugeicons/core-free-icons/ViewOffSlashIcon';

type HugeIconProps = Omit<ComponentProps<typeof HugeiconsIcon>, 'icon'>;
type HugeIconData = ComponentProps<typeof HugeiconsIcon>['icon'];

const createIcon = (icon: HugeIconData) =>
  forwardRef<SVGSVGElement, HugeIconProps>(({ strokeWidth = 1.8, ...props }, ref) => (
    <HugeiconsIcon ref={ref} icon={icon} strokeWidth={strokeWidth} {...props} />
  ));

const CalendarBase = createIcon(Calendar03Icon);
const TrashBase = createIcon(Delete02Icon);

export const AlertTriangle = createIcon(Alert02Icon);
export const ArrowDown = createIcon(ArrowDown01Icon);
export const ArrowRight = createIcon(ArrowRight02Icon);
export const ArrowUp = createIcon(ArrowUp01Icon);
export const ArrowUpDown = createIcon(Sorting01Icon);
export const Bell = createIcon(BellIcon);
export const Calendar = CalendarBase;
export const CalendarDays = createIcon(Calendar01Icon);
export const CalendarIcon = CalendarBase;
export const Check = createIcon(Tick02Icon);
export const CheckSquare = createIcon(CheckmarkSquare02Icon);
export const ChevronDown = createIcon(ChevronDownIcon);
export const ChevronLeft = createIcon(ChevronLeftIcon);
export const ChevronRight = createIcon(ChevronRightIcon);
export const Clock = createIcon(Clock01Icon);
export const Edit2 = createIcon(PencilEdit02Icon);
export const Eraser = createIcon(EraserIcon);
export const Eye = createIcon(ViewIcon);
export const EyeOff = createIcon(ViewOffSlashIcon);
export const Flame = createIcon(FireIcon);
export const Folder = createIcon(Folder01Icon);
export const Frown = createIcon(FrownIcon);
export const GripVertical = createIcon(GripVerticalIcon);
export const Heart = createIcon(HeartIcon);
export const HelpCircle = createIcon(HelpCircleIcon);
export const Layers = createIcon(Layers01Icon);
export const ListTodo = createIcon(Task01Icon);
export const Meh = createIcon(MehIcon);
export const MoveRight = createIcon(MoveRightIcon);
export const Plus = createIcon(Add01Icon);
export const RefreshCw = createIcon(RefreshIcon);
export const Repeat = createIcon(RepeatIcon);
export const Settings = createIcon(Settings01Icon);
export const ShieldAlert = createIcon(Shield02Icon);
export const Smile = createIcon(SmileIcon);
export const Square = createIcon(StopIcon);
export const Trash = TrashBase;
export const Trash2 = TrashBase;
export const X = createIcon(Cancel01Icon);
